### PR TITLE
Ft user login endpoint

### LINKED ISSUE #23: Implement User Login Endpoint [Front-end]

### PR DESCRIPTION
**Pull request by jothamardel**

### CODE REVIEW

**Review by jason-ibisi — COMMENTED** [review]
Not linked to a Project, Issue and Milestone.
Please fix.

**Review by jason-ibisi — APPROVED** [review]

**Comment by Ose-Me** [comment]
the emergency contact details added to the sign up page are already in the update profile page

**Comment by jason-ibisi** [comment]
Please please please guys, test your pages against its endpoints.

**Review by nonsoo24 — APPROVED** [review]

**Review by Ose-Me — APPROVED** [review]

**Comment by jason-ibisi** [comment]
Hello Guys, is there a reason this branch hasn't been merged ?

**Pull request merged**
