### PR TITLE
Ft confirmation message modal

### LINKED ISSUE #25: Update app.properties on Team-075-ERS repo
# the product
name:
sdgs:
repos:
app.urls:
codacy.urls:
app.forCOVID19: NO
app.industries:

# the codebase
code.languages:
code.frameworks:
code.opensource.facebook:
code.opensource.contributions:

# the team
team.name:
team.ttls:
team.mentors:
team.slackchannel:

# == DO NOT EDIT ==
# about the program
# ================= 
program.cohort:1
program.name:BuildforSDG
program.community:https://github.com/BuildForSDG

### LINKED ISSUE #27: Create request sent modal component

### PR DESCRIPTION
**Pull request by Ose-Me**
## Description
created a modal message component that shows up when the user clicks the help button and the eye witness button

All pull requests should be related to open issues. Indicate the issue(s) bellow and remove this line:
Fixes #24

### CODE REVIEW

**Review by jothamardel — CHANGES_REQUESTED** [review]
Let's have the modals in separate folders in the component folder.

**Review by jothamardel — DISMISSED** [review]

**Review by jason-ibisi — APPROVED** [review]

**Review by jason-ibisi — CHANGES_REQUESTED** [review]
@Ose-Me Please review conflicts

**Comment by nonsoo24** [comment]
@Ose  Please review conflicts

**Review by nonsoo24 — CHANGES_REQUESTED** [review]
@Ose-Me Please review conflicts

**Comment by Ose-Me** [comment]
> @Ose-Me Please review conflicts

i don't think i have write access to resolve conflicts

**Review by nonsoo24 — DISMISSED** [review]

**Review by nonsoo24 — DISMISSED** [review]

**Review by jason-ibisi — APPROVED** [review]

**Review by jason-ibisi — CHANGES_REQUESTED** [review]
Please populate the app.properties file. See the backend https://github.com/BuildForSDG/Team-075-ERS-API/blob/develop/app.properties for guidance.

**Review by jason-ibisi — APPROVED** [review]

**Review by jothamardel — APPROVED** [review]

**Pull request merged**
