### PR TITLE
Ft subscribe

### LINKED ISSUE #117: Subscribe response unit to push notification

### PR DESCRIPTION
**Pull request by jothamardel**
## Description
Ask for permission to allow notifications and
Automatically subscribes response unit to push notification.

## Screenshots (if applicable, else remove this line / section)
Screenshot from 2020-06-10 23-21-04
Screenshot from 2020-06-10 23-21-15

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by jason-ibisi** [comment]
The cards are showing IDs instead of names

**Comment by jothamardel** [comment]
> The cards are showing IDs instead of names

The response doesn't have a name property.
Screenshot from 2020-06-11 00-20-33

**Review by oluwaseunsamuel — DISMISSED** [review]

**Review by Ose-Me — COMMENTED** [review]
please resolve conflict

**Review by oluwaseunsamuel — DISMISSED** [review]

**Review by Ose-Me — DISMISSED** [review]

**Review by oluwaseunsamuel — APPROVED** [review]

**Review by Ose-Me — APPROVED** [review]

**Comment by jason-ibisi** [comment]
Please update the cards to show user names as the reports now contain user details

**Review by nonsoo24 — APPROVED** [review]

**Pull request merged**
