### PR TITLE
feat: Session persistence

### LINKED ISSUE #30: Implement Session Persistence [Front-end]

### PR DESCRIPTION
**Pull request by jothamardel**
It allows users pick up from when they closed the application.

### CODE REVIEW

**Comment by Ose-Me** [comment]
getting this error when trying to run
./src/redux/store.js
Module not found: Can't resolve 'redux-persist'

**Comment by jothamardel** [comment]
> getting this error when trying to run
> ./src/redux/store.js
> Module not found: Can't resolve 'redux-persist'

**Install the package npm i or yarn**

**Comment by Ose-Me** [comment]
> > getting this error when trying to run
> > ./src/redux/store.js
> > Module not found: Can't resolve 'redux-persist'
> 
> **Install the package npm i or yarn**

Already have that installed

**Comment by jothamardel** [comment]
> > > getting this error when trying to run
> > > ./src/redux/store.js
> > > Module not found: Can't resolve 'redux-persist'
> > 
> > 
> > **Install the package npm i or yarn**
> 
> Already have that installed

**How did you get redux-persist when it's not merged?**

**Comment by Ose-Me** [comment]
> > > > getting this error when trying to run
> > > > ./src/redux/store.js
> > > > Module not found: Can't resolve 'redux-persist'
> > > 
> > > 
> > > **Install the package npm i or yarn**
> > 
> > 
> > Already have that installed
> 
> **How did you get redux-persist when it's not merged?**

i did a fetch on this branch

**Review by Ose-Me — APPROVED** [review]

**Review by jason-ibisi — APPROVED** [review]

**Pull request merged**
