### PR TITLE
feat: Eye witness button and fixed background

### LINKED ISSUE #8: Homepage
Homepage

### PR DESCRIPTION
**Pull request by Ose-Me**
## Description
This includes the Eye witness button on the homepage and the fixed background rings for the other pages
Fixes #8

### CODE REVIEW

**Review by nonsoo24 — DISMISSED** [review]

**Review by nonsoo24 — DISMISSED** [review]

**Comment by jothamardel** [comment]
This branch will conflict with #22

**Comment by Ose-Me** [comment]
> This branch will conflict with #22 
am i supposed to go redo what i did again?

**Comment by jason-ibisi** [comment]
> > This branch will conflict with #22
> > am i supposed to go redo what i did again?

One pull request should be merged first and then resolve the conflicts in the second pull requests

**Comment by jothamardel** [comment]
I've resolved the conflicts.

**Review by jothamardel — DISMISSED** [review]

**Review by jothamardel — APPROVED** [review]

**Review by jason-ibisi — APPROVED** [review]

**Pull request merged**
